import {ProductModel} from "../products/model";
import {ROLES, UserModel} from "../users/model";

export default async function create() {
    await ProductModel.deleteMany({});
    await ProductModel.create({photo:' https://www.google.com/search?q=fifa+20&client=firefox-b-d&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjetOqThrL2AhVOh_0HHeKKBPkQ_AUoAnoECCsQBA&biw=1159&bih=1280&dpr=1#imgrc=j9hKBXDlcRjFIM', name: 'Fifa 20', price:'20', stock:'2' })
    await ProductModel.create({photo:' https://www.google.com/search?q=fifa+19&tbm=isch&ved=2ahUKEwjvqc2UhrL2AhWNDOwKHdrlCbgQ2-cCegQIABAA&oq=fifa+19&gs_lcp=CgNpbWcQAzIICAAQgAQQsQMyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQ6BwgAELEDEEM6BAgAEEM6CwgAEIAEELEDEIMBUP8HWL4JYMELaABwAHgAgAFriAGCApIBAzIuMZgBAKABAaoBC2d3cy13aXotaW1nwAEB&sclient=img&ei=a_QkYq_INo2ZsAfay6fACw&bih=1280&biw=1159&client=firefox-b-d#imgrc=-EciD4C09JWvaM', name: 'Fifa 19', price:'30', stock:'67' })
    await ProductModel.create({photo:' https://www.google.com/search?q=elden+ring&tbm=isch&ved=2ahUKEwiY07WchrL2AhUh2OAKHUa8DpoQ2-cCegQIABAA&oq=elden+ring&gs_lcp=CgNpbWcQAzILCAAQgAQQsQMQgwEyCwgAEIAEELEDEIMBMgQIABADMgQIABADMgsIABCABBCxAxCDATILCAAQgAQQsQMQgwEyBAgAEAMyCwgAEIAEELEDEIMBMgQIABADMgQIABADOgcIABCxAxBDOgQIABBDOgUIABCABDoICAAQgAQQsQM6CAgAELEDEIMBOgoIABCxAxCDARBDUPkFWNYMYI0OaABwAHgAgAFgiAG9B5IBAjExmAEAoAEBqgELZ3dzLXdpei1pbWfAAQE&sclient=img&ei=fPQkYpilEaGwgwfG-LrQCQ&bih=1280&biw=1159&client=firefox-b-d#imgrc=cjc7GoLP04wZbM', name: 'Elden ring', price:'80', stock:'4' })
    await ProductModel.create({photo:' https://www.google.com/search?q=world+of+warcraft&tbm=isch&ved=2ahUKEwi868yihrL2AhXO8LsIHQnACngQ2-cCegQIABAA&oq=world+of&gs_lcp=CgNpbWcQARgAMggIABCABBCxAzIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDoKCAAQsQMQgwEQQzoLCAAQgAQQsQMQgwE6BAgAEAM6CAgAELEDEIMBOgQIABBDOgcIABCxAxBDUL0FWMINYOcVaABwAHgAgAFriAGNBpIBAzguMZgBAKABAaoBC2d3cy13aXotaW1nwAEB&sclient=img&ei=ifQkYvyCD87h7_UPiYCrwAc&bih=1280&biw=1159&client=firefox-b-d#imgrc=hTn3thQQPuNZfM', name: 'World of Warcraft', price:'2900', stock:'2' })
    await ProductModel.create({photo:' https://www.google.com/search?q=league+of+leguends+logo&tbm=isch&ved=2ahUKEwiz75e5hrL2AhWO_bsIHT9QBmYQ2-cCegQIABAA&oq=league+of+leguends+logo&gs_lcp=CgNpbWcQAzIFCAAQgAQyBggAEAoQGDoECAAQQzoECAAQHlCBLlizNGCzNWgAcAB4AIABZ4gBigSSAQM1LjGYAQCgAQGqAQtnd3Mtd2l6LWltZ8ABAQ&sclient=img&ei=uPQkYrOzJY777_UPv6CZsAY&bih=1280&biw=1159&client=firefox-b-d#imgrc=6XTc5saPQUmzVM', name: 'League of Leguends', price:'50', stock:'2' })
    await UserModel.deleteMany({});
    await UserModel.create({password:'123', email:'a@gmail.com', role:ROLES.NORMAL})
    await UserModel.create({password:'123', email:'b@gmail.com', role:ROLES.ADMIN})
}