[[section-introduction-and-goals]]

== Introducción y objetivos

DeDe es un proyecto para la asignatura de Arquitectura de Software de la Universidad de Oviedo. Esta versión será desarrollada por los miembros del equipo es1c que son:


- Héctor Martín Gutierrez
- Laura Vigil Laruelo
- Ivan Valle Soto
- Álvaro López Fueyo

DeDe es un sistema de venta online descentralizado que respeta la privacidad de los clientes.

=== Resumen de requisitos


La aplicación se ejecutará en el servidor, y la información del usuario se almacenará en su pod.
Para obtener información de otros usuarios, la aplicación consultará sus correspondientes pods. Todos estos requisitos son compatibles con el proyecto SOLID, ya que la información de los usuarios no se almacena de forma centralizada.

En la aplicación web los usuarios podrán comprar, el sistema calculará los costes de envío consultando la dirección deseada del usuario en su pod y calculando los costes de acuerdo a la distancia del centro de distribución a dicha dirección.

Los usuarios podrán confirmar la compra como ver sus pedidos realizados.

==== Requisitos técnicos

Para el despliegue del sistema se utilizarán contenedores docker o en su defecto ejecutando restapi.

Se controlará el correcto funcionamiento mediante las siguientes tipos de pruebas:

* Pruebas unitarias
* Pruebas de aceptación
* Pruebas de carga

=== Objetivos de calidad

[options="header",cols="1,2"]
|===
|Objetivo de calidad |Motivación
| Usabilidad
| La aplicación debería de poder ser usada por cualquier tipo de usuario independientemente de su nivel.

| Privacidad
|  La gestión de información es descentralizada.

| Seguridad
| La aplicación no debería de tener ninguna vulnerabilidad.

| Portabilidad
|  Que la aplicación pueda adaptarse de forma correcta a distintos dispositivos.
|===

=== Stakeholders

[options="header",cols="1,2"]
|===
|Role |Expectativas
| Profesores del curso
| Implementar y mostrar un proyecto que refleje lo explicado en clase.

| Clientes
| Sea intuitiva y fácil de utilizar independientemente del nivel.

| Administrador
| Encargado  de solucionar los futuros problemas.
|===
