[[section-solution-strategy]]
== Estrategia de Solución


=== Decisiones Técnicas
Para el desarrollo del proyecto se han tomado las siguientes decisiones:
[options="header"]
|===
| Nombre de la tecnológia        | Objetivo
| TypeScript   | Lenguaje principal del proyecto
| React     | Biblioteca que facilitará el desarrollo de la interfaz gráfica
| MongoDB | Base de datos que permitirá guardar los datos de los usuarios,centros de distribución y diferentes productos
| Github | Herramienta de control de versiones que mejora el trabajo en equipo
|SOLID | Especificación que permite a las personas almacenar sus datos de forma segura en almacenes de datos descentralizados llamados Pods.
|Heroku | Utilizaremos Heroku para desplegar nuestra aplicación, de este modo no habrá preocupación por la infraestructura.
|Geocoding | Consumiremos una API externa para calcular el precio de los envios.

|===
=== Decisiones sobre la descomposición de alto nivel del sistema

Se ha decidido utilizar el patrón arquitectónico MVC para desarrollar la aplicación

=== Decisiones para lograr objetivos de calidad

Para lograr cumplir con los diversos objetivos de calidad hemos realizado las siguientes acciones:

* *Privacidad:* Para asegurar la mejor privacidad a los usuarios se usan los PODs de SOLID,los cuáles nos permiten almacenar los datos de usuario en un formato interoperable, y brindarles  controles de autorización.
* *Usabilidad:* Para mejorar este objetivo nuestras interfaces son lo más fluidas, simples e intuitivas posibles, ayudandonos siempre de metáforas como por ejemplo el icono de la casa para marcar el inicio o el de un carro para el carrito del cliente.
* *Eficiencia:* Como el uso de los Pods de SOLID ralentiza la aplicación, solo será necesario tener iniciado el POD de usuario en otra ventana e introducirlo en el login, la aplicación no lo pedirá nunca más.
* *Testeabilidad:* Se han realizado diferentes tipos de test para comprobar la robustez del proyecto, entre los que destacamos test unitarios, de usabilidad y test de carga.

=== Decisiones para la organización
* *Reuniones*
Durante la semana se ha planificado una reunión presencial, en la que se han expuesto los puntos ha realizar antes de la siguiente, además se han tratado los problemas u obstaculos encontrados, todo esto ha quedado reflejado a través de actas, disponibles en nuestra wiki, formando un total de más de 18 reuniones.
Cuando ha surgido algun problema durante la realización del proyecto se ha podido planificar reuniones online a través de Discord.

* *Github*
Para poder realizar un buen control de versiones del proyecto se ha utilizado Github, donde se crearon diferentes ramas:
- Master: producto final.
- Develop: rama en la que se encuentra el producto en desarrollo.
- Nombre del miembro: dentro de develop cada miembro tiene una rama en la que pueden trabajar.
- Hotfix: rama para hacer cambios rápidos a la rama principal sin tener que pasar por otras de más bajo nivel. Esta rama se ha dividido en hotfix a secas para cambios de proyecto, hotfixDocu para cambios en documentación y hotfixTest para solucionar problemas de testing.
- Backend: en esta rama se trabaja todo el código del Backend de manera conjunta. Añadiendo en la parte final del proyecto la rama backendFinal a partir de la release v1.0.0.
- Nombre/documentacion: aquí cada miembro del equipo subió las partes de la documentación que fue desarrollando al principio, donde se planteo un esbozo de lo que finalmente sería la aplicación


Todo lo realizado en el proyecto, tanto problemas como distintas aportaciones se han recogido a modo de issues en el repositorio de github del proyecto. Cada issue ha sido asignada a distintos miembros del equipo y cerrada por otros. Añadiendo distintas etiquetas que hacen referencia a la parte del proyecto correspondiente.

Por otro lado, los miembros del equipo han realizado pull request antes de mergear con otra rama, estos han sido aceptados por compañeros revisando el código antes de que realizar el merge. Salvo para casos en los que la rama a mergear era una simple actualización.