[[section-runtime-view]]
== Runtime View
Los siguientes casos de secuencias explican algunos de los escenarios que se pueden dar lugar en dede

[role="arc42help"]

=== Login de Usuario
[plantuml,"Login_diagrama",png]
----
@startuml
actor Usuario 
entity Dede
database POD
Usuario-> Dede: Petición de autenticación
Dede-> POD: Comprobación de credenciales
alt usuario existe

    POD -> Dede:Devuelve al usuario
    Dede->Usuario:Redirección a página principal con usuario identificado 

else usuario ya existe
    POD -> Dede: Mensaje de error
end

@enduml
----
=== Registro de usuarios
[plantuml,"Registro_diagrama",png]
----
@startuml
actor Usuario
entity Dede
database POD
Usuario-> Dede :Introducción de credenciales
Dede->POD:Compración del usuario
alt usuario no existe

    POD -> Dede: Usuario creado

else usuario ya existe
    POD -> Dede: Mensaje de error
end
@enduml
----
=== Añadir un producto al carro
[plantuml,"AñadirCarro_diagrama",png]
@startuml
actor Usuario
entity Dede
database BBDD
Usuario-> Dede: Selecciona un producto
Dede-> BBDD: Peticion:añadir el producto al carro del usuario
BBDD-> Dede:Petición aceptada 
Dede->Usuario:Notificación del añadido
@endtuml
=== Compra de los productos
[plantuml,"Compra_diagrama",png]
@startuml
actor Usuario
entity Dede
database BBDD
Usuario-> Dede:Compra de los productos
Dede-> BBDD: Petición guardado productos al usuario
BBDD-> Dede: Devuelve información necesaria
Dede-> Usuario: Pedir datos necesarios para compra
Usuario-> Dede:Introducción datos necesarios
Dede-> BBDD: Comprobación datos
BBDD-> Dede:  Devuelve información necesaria
Dede-> Usuario: Notificación de la compra
@endtuml