[[section-concepts]]
== Conceptos transversales

=== Conceptos de dominio
[options="header",cols="1,2"]
|===
|Rol | Explicación
|Usuario | Representa un usuario de la aplicación, toda su información se guardará en un POD.

|Posición actual del usuario | El objetivo es que se conozca la posición actual para,  en el caso de enviar un pedido, se pueda calcular el coste de envio.

|Productos | Lista de productos disponibles con toda la información relevante.
|===

==== Conceptos de experiencia de usuario

La aplicación está desarrollada para que el usuario pueda interaccionar con ella de manera sencilla, no es necesario que tenga conocimientos previos, pero como es lógico
si ya se encuentra familiarizado con plataformas de compra electrónica como Steam u Origin, siempre le será más sencillo.

El usuario podrá identificarse haciendo clic en la parte derecha del panel introduciendo su POD, o bien acceder a crear un POD en la página de SOLID, se le pone a disposición el enlace al usuario.
La única forma de compra y acceso a la aplicación es la de usuario registrado en un POD, nos tomamos muy enserio la privacidad y creemos que esta es la mejor manera de interacción con nuestro sistema.


==== Conceptos de seguridad y protección

En líneas generales, nuestra aplicación es segura. Hemos utilizado los principios SOLID, esto es que los datos de los usuarios serán almacenados de forma segura en almacenes de datos llamados PODS.
Los PODS (Personal online data stores) pueden contener cualquier tipo de información, en nuestro caso contiene email que será el usuario, password, nombre, apellido, teléfono, país, provincia, ciudad, código postal, calle, número, piso y letra del piso.
El acceso a los datos de los PODS se puede restringir y controlar de manera segura, eligiendo las reglas de acceso determinadas.

Se ha prestado especial atención en fortificar la base de datos, ya que muchos de los ataques conocidos se centran en esta parte de las aplicaciones, separando los PODS de usuarios de la propia base de datos
de la aplicación.


==== Arquitectura y patrones de diseño

Una de las decisones más importantes a la hora de desarrollar una aplicación es pensar en el diseño, uno de los referentes que hemos tenido en cuenta es el libro de Erich Gamma, _Design Patterns_. En esta
obra se explican algunos de los principios más populares para el desarrollo de software mantenible y de calidad. Además tambien hemos consultado multitud de artículos donde se explican tecnicas
para un buen desarrollo y un bajo acoplamientro, con esto hemos decidido aplicar varias cosas:

* Modularidad: esto es que la aplicación se encuentra compuesta por varios componentes, que juntandose hacen una aplicación funcional. Si uno de los componentes cambia, el resto no se verá afectado.

* Fachada: haciendo referencia al patrón de diseño arquitectónico, hacemos la separación e interacción necesaria con SOLID para que todo funcione y se mantenga un minimo acoplamiento.

* MVC (Modelo vista controlador): para poder gestionar las vistas en el frontend con las peticiones en el backend.


==== "_Bajo el capó_" conceptos de desarrollo

La aplicación cuenta con un frontend y un backend perfectamente comunicados. La parte del frontend es la que ve el usuario y a la que tendrá acceso, aquí se incluyen todos los menus, botones y vistas de la aplicación.

Tanto la lógica de la aplicación como la base de datos forman parte del backend, el frontend hará peticiones al backend y todo esta sincronizado para que así ocurra.
Como ya se menciono anteriormente, los datos de usuario son guardados en un POD, separandose de la base de datos de productos de la aplicación para seguir los principios SOLID y aumentar la seguridad.

==== Conceptos operativos

Las operaciones básicas que se pueden realizar desde la aplicación desde el rol de usuario son:

* Autenticación de usuario: Hace referencia a identificarse en la aplicación como usuario registrado mediante su POD.

* Compra de producto: El usuario podrá adquirir los productos que considere, como si se tratase de un comercio fisico.

* Operaciones en carrito: Hace referencia a operaciones de añadir o eliminar productos dentro del carrito.

* Filtrar por categorias: Una función que consiste en que el usuario pueda ver de manera más concreta determinado tipo de productos.

* Filtrar por nombre: Una función que consiste en que el usuario pueda buscar un producto por su nombre.

En el siguiente diagrama se puede apreciar de forma gráfica las operaciones que puede realizar el usuario explicadas anteriormente:
[plantuml, "conceptos operativos",png]
----
left to right direction
usuario as ac1

(Autenticación de usuario) as (a)
(Compra de producto) as (c)
(Operaciones en carrito) as (o)
(Filtrar por categorias) as (f)
(Filtrar por nombre) as (n)

ac1 --> a
ac1 --> c
ac1 --> o
ac1 --> f
ac1 --> n
----


